-- V1__init.sql

CREATE TABLE tb_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),

    CONSTRAINT tb_order_pkey PRIMARY KEY (id),
    CONSTRAINT tb_order_status_check CHECK (status IN ('FAILED','PENDING', 'PROCESSED'))
);